### ISSUE TITLE
Create a Sidebar component

### ISSUE THREAD

**Issue by gmagnenat** [aylinhyusmen/reddit#4]
The sidebar should have a list of popular topics.

When the user click on a link it runs the query and re-render the feed with the selected topic.

**Comment by nghiab1910673** [comment]
Can you assign me, please? I doing homework about contribute to issues and I think i can try this issue. Can you help a newbie like me, sir?

**Comment by gmagnenat** [comment]
Feel free to fork the project and submit a PR

**Comment by nghiab1910673** [comment]
> Feel free to fork the project and submit a PR

Thank you very much. I will submit it soon
